work_dir: /cvhci/temp/ywei2/work_dir/6_120/XXXXXXXXXX
weights: /cvhci/temp/ywei2/work_dir/6_120/6_120/XXXXXXXXXX
ignore_weights: [encoder_q.fc, encoder_q_motion.fc, encoder_q_bone.fc, encoder_q_acceleration.fc, encoder_q_rotation_axis.fc, encoder_q_omega.fc, encoder_k, encoder_k_motion, encoder_k_bone, encoder_k_acceleration, encoder_k_rotation_axis, encoder_k_omega, queue, queue_motion, queue_bone, queue_acceleration, queue_rotation_axis, queue_omega, mlp2j, mlp2m, mlp2b, mlp2a, mlp2r, mlp2o]

# feeder
train_feeder: feeder.ntu_feeder.Feeder_single
train_feeder_args:
  data_path: /cvhci/temp/ywei2/NTU120_frame50/xsetup/train_position.npy
  label_path: /cvhci/temp/ywei2/NTU-RGB-D-120/xsetup/train_label.pkl 
  shear_amplitude: -1
  temperal_padding_ratio: -1
  camera_view: -1
  motion_scale: -1
  mmap: True
  true_timeline: True
test_feeder: feeder.ntu_feeder.Feeder_single
test_feeder_args:
  data_path: /cvhci/temp/ywei2/NTU120_frame50/xsetup/val_position.npy
  label_path: /cvhci/temp/ywei2/NTU-RGB-D-120/xsetup/val_label.pkl 
  shear_amplitude: -1
  temperal_padding_ratio: -1
  camera_view: -1
  motion_scale: -1
  mmap: True
  true_timeline: True

# model
model: net.crossclr_6views.CrosSCLR
model_args:
  base_encoder: net.st_gcn.Model
  pretrain: False
  teacher_student: False
  # feature_dim: 128
  # queue_size: 32768
  # momentum: 0.999
  # Temperature: 0.07
  # mlp: True
  in_channels: 3
  hidden_channels: 16
  hidden_dim: 256
  num_class: 120
  dropout: 0.5
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'
  edge_importance_weighting: True

# optim
nesterov: False
weight_decay: 0.0
base_lr: 3.
optimizer: SGD
step: [80]

# training
device: [0]
batch_size: 128
test_batch_size: 128
num_epoch: 100
view: 'omega'

# log
save_interval: -1
eval_interval: 5
